# Generated by Django 5.2 on 2025-04-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("upload_timestamp", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="")),
            ],
        ),
    ]
